neg_prompt = '(nsfw:2), paintings, sketches, (worst quality:2), (low quality:2), ' \
             'lowers, normal quality, ((monochrome)), ((grayscale)), logo, word, character, bad hand, tattoo, (username, watermark, signature, time signature, timestamp, artist name, copyright name, copyright),'\
             'low res, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, glans, extra fingers, fewer fingers, strange fingers, bad hand, mole, ((extra legs)), ((extra hands))'
pos_prompt_with_cloth = 'raw photo, masterpiece, chinese, {}, solo, medium shot, high detail face, looking straight into the camera with shoulders parallel to the frame, photorealistic, best quality'
pos_prompt_with_style = '{}, upper_body, raw photo, masterpiece, solo, medium shot, high detail face, photorealistic, best quality'

base_models = [
    {'name': 'leosamsMoonfilm_filmGrain20',
    'model_id': 'ly261666/cv_portrait_model',
    'revision': 'v2.0',
    'sub_path': "film/film",
    'style_list': ['工作服(Working suit)', '盔甲风(Armor)','T恤衫(T-shirt)','汉服风(Hanfu)','女士晚礼服(Gown)','赛博朋克(Cybernetics punk)','凤冠霞帔(Chinese traditional gorgeous suit)','休闲生活风(Casual Lifestyle)','梅花女孩(Chinese Girl among Plum Blossoms)','芭比娃娃(Barbie Doll)','白月光(Innocent Girl in White Dress)','优雅公主(Elegant Princess)','鬼马少女(Pixy Girl)','白雪公主(Snow White)']},
    {'name': 'MajicmixRealistic_v6',
    'model_id': 'YorickHe/majicmixRealistic_v6',
    'revision': 'v1.0.0',
    'sub_path': "realistic",
    'style_list': ['冬季汉服(Chinese winter hanfu)', '校服风(School uniform)', '婚纱风(Wedding dress)', '夜景港风(Hong Kong night style)', '雨夜(Rainy night)', '模特风(Model style)', '机车风(Motorcycle race style)', '婚纱风-2(Wedding dress 2)','拍立得风(Polaroid style)', '仙女风(Fairy style)', '古风(traditional chinese style)', '壮族服装风(Zhuang style)', '欧式田野风(European fields)', '雪山羽绒服风(Jacket in Snow Mountain)', '旗袍风(Cheongsam)', '日系和服风(Kimono Style)', '贵族公主风(Princess costum)','机械风(Mechanical)','林中鹿女风(deer girl)','漫画风(cartoon)','绿野仙踪(Wizard of Oz)','藏族风(ZangZu Style)','红发礼服风(Red Style)','多巴胺风格(Colourful Style)','国风(GuoFeng Style)','复古风(Retro Style)','印度风(India)','海洋风(ocean)','花园风(flowers)','主题乐园风(Disneyland)','绿茵球场风(Soccer Field)','中华刺绣风(Embroidery)','蒙古草原风(Mongolian)','梦幻深海风(Sea World)','火红少女风(Flame Red Style)', '藏族服饰风(tibetan clothing style)', '萧瑟秋天风(bleak autumn style)', '秋日胡杨风(autumn populus euphratica style)', '丁达尔风(Tyndall Light)', '哥特洛丽塔(Gothic Lolita)', '复古风(retro style)', '绅士风(gentleman style)','西部牛仔风(west cowboy)', '嘻哈风(hiphop style)', '洛丽塔(lolita)', '女巫风(witch style)', '女仆风(maid style)','圣诞风(Christmas)','敦煌风(Dunhuang)','苗族服装风(Miao style)','时尚墨镜风(fashionglasses)','夏日海滩风(Summer Ocean Vibe)','西部牛仔风(Cowboy style)', '炫彩少女风(Colorful rainbow style)', '京剧名旦风(Female role in Peking opera)', '自然清冷风(Cool tones)', '中国新年风(Chinese New Year Style)', '男士西装风(Men\'s Suit)', '漫游宇航员(Roaming Astronaut)', '复古军装风(Retro military uniform)', '花环洛丽塔(Flora Lolita)']},
]

styles = [
    {'name': '工作服(Working suit)',
     'img': './style_image/Working_suit.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing high-class business/working suit, simple background, high-class pure color background'},
    {'name': '盔甲风(Armor)',
     'img': './style_image/Armor.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing silver armor, simple background, high-class pure color background'},
    {'name': 'T恤衫(T-shirt)',
     'img': './style_image/T-shirt.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing T-shirt, simple background, high-class pure color background'},
    {'name': '汉服风(Hanfu)',
     'img': './style_image/Hanfu.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing beautiful traditional hanfu, upper_body, simple background, high-class pure color background'},
    {'name': '女士晚礼服(Gown)',
     'img': './style_image/Gown.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing an elegant evening gown, simple background, high-class pure color background'},
    {'name': '赛博朋克(Cybernetics punk)',
     'img': './style_image/Cybernetics_punk.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'white hair, neon glowing glasses, cybernetics, punks, robotic, AI, NFT art, Fluorescent color, ustration'},
    {'name': '凤冠霞帔(Chinese traditional gorgeous suit)',
     'img': './style_image/Chinese_traditional_gorgeous_suit.jpg',
     'model_id': 'ly261666/civitai_xiapei_lora',
     'revision': 'v1.0.0',
     'bin_file': 'xiapei.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'red, hanfu, tiara, crown'},
     {'name': '冬季汉服(Chinese winter hanfu)',
     'img': './style_image/Chinese_winter_hanfu.jpg',
     'model_id': 'YorickHe/Winter_hanfu_lora',
     'revision': 'v1.0.0',
     'bin_file': 'Winter_Hanfu.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': 'red hanfu, winter hanfu, cloak, photography, warm light, sunlight, majestic snow scene,  close-up, front view, soft falling snowflakes, jewelry, enchanted winter wonderland'},
     {'name': '校服风(School uniform)',
     'img': './style_image/School_uniform.jpg',
     'model_id': 'YorickHe/JK_uniform_lora',
     'revision': 'v1.0.0',
     'bin_file': 'jk_uniform.safetensors',
     'multiplier_style': 0.2,
     'multiplier_human': 0.95,
     'add_prompt_style': 'JK_style, white short-sleeved JK_shirt, dark blue JK_skirt, bow JK_tie, close-up, looking at viewer, sweet smile, night, Tokyo street, night city scape'},
     {'name': '婚纱风(Wedding dress)',
     'img': './style_image/Wedding_dress.jpg',
     'model_id': 'YorickHe/outdoor_photo_lora',
     'revision': 'v1.0.0',
     'bin_file': 'outdoor_photo_v2.0.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': 'white wedding dress, 1girl, summer, flower, happy atmosphere, sunlight, Waist Shot'},
     {'name': '夜景港风(Hong Kong night style)',
     'img': './style_image/Hong_Kong_night_style.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, close-up, face shot, stylish outfit, fitted jeans, oversized jacket, fashionable accessories, cityscape backdrop, rooftop or high-rise balcony, dynamic composition, engaging pose, soft yet striking lighting, shallow depth of field, bokeh from city lights, naturally blurred background'},
     {'name': '雨夜(Rainy night)',
     'img': './style_image/Rainy_night.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 0.95,
     'add_prompt_style': 'standing in the rain, wet, wet clothes, wet hair, face Shot, front view, close-up, cityscape, cold lighting, realistic, cinematic lighting, photon mapping, radiosity, physically-based rendering'},
     {'name': '模特风(Model style)',
     'img': './style_image/Model_style.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, balenciaga, close-up, fashion, streets of new york, new york, modeling for Balenciaga, natural skin texture, dynamic pose, rouge, film grain'},
     {'name': '机车风(Motorcycle race style)',
     'img': './style_image/Motorcycle_race_style.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.4,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, close-up, wearing racing clothes, motorbike clothes, modeling, playful, futuristic, city street background, at night, cool atmospheric, realistic'},
     {'name': '婚纱风-2(Wedding dress 2)',
     'img': './style_image/Wedding_dress_2.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.4,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, close-up, wearing wedding dress, white, film grain, sunlight, sun flare, lens flare, field of white roses, high fashion, top model'},
    {'name': '拍立得风(Polaroid style)',
     'img': './style_image/Polaroid_style.jpg',
     'model_id': 'YorickHe/polaroid_lora',
     'revision': 'v1.0.0',
     'bin_file': 'InstantPhotoX3.safetensors',
     'multiplier_style': 0.4,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, close-up, simple clothes, front view, looking straight into the camera, film grain, flash, enhanced flash, dark background, polaroid, instant photo, realistic face'},
     {'name': '仙女风(Fairy style)',
     'img': './style_image/Fairy_style.jpg',
     'model_id': 'YorickHe/fairy_lora',
     'revision': 'v1.0.0',
     'bin_file': 'fairy.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'a beautiful fairy standing in the middle of a flower field, petals, close-up, warm light, light green atmosphere, white atmosphere, in the style of celebrity photography, soft, romantic scenes, flowing fabrics, light white and light orange, high resolution'},
     {'name': '古风(traditional chinese style)',
     'img': './style_image/traditional_chinese_style.jpg',
     'model_id': 'iotang/lora_testing',
     'revision': 'v5',
     'bin_file': 'MoXinV1.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '(best quality, hanfu, Chinese traditional ink painting:1.8), close-up, song, anxiang, chinese_clothes, ornaments, topknot, perfect eyes, perfect face, soft smile'},
    {'name': '壮族服装风(Zhuang style)',
     'img': './style_image/Zhuang_style.jpg',
     'model_id': 'iotang/lora_testing',
     'revision': 'v5',
     'bin_file': 'zhuangnv.safetensors',
     'multiplier_style': 0.75,
     'multiplier_human': 0.95,
     'add_prompt_style': '((best quality)), close-up, portrait, ((zhuangzunv)), ornaments, jewelry, headwear, ((beautiful embroidery, floral print, marvelous design)), perfect eyes, perfect face, gentle black hair, smile'},
    {'name': '欧式田野风(European fields)',
     'img': './style_image/European_fields.jpg',
     'model_id': 'iotang/lora_testing',
     'revision': 'v5',
     'bin_file': 'edgEuropean_Vintage.safetensors',
     'multiplier_style': 0.55,
     'multiplier_human': 0.95,
     'add_prompt_style': 'focused, (edgEV, wearing edgEV_vintage dress), (field, natural lighting, detailed background, cinematic lighting), (gentle hair:1.1), windy hair, perfect eyes, perfect face'},
    {'name': '雪山羽绒服风(Jacket in Snow Mountain)',
     'img': './style_image/Jacket_in_Snow_Mountain.jpg',
     'model_id': 'iotang/lora_testing',
     'revision': 'v7',
     'bin_file': 'puffy_jacket-1.0.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.9,
     'add_prompt_style': 'close-up, fur collar, ((jacket)), shirt, pants, winter, (bright sunny day, snow mountain, alpine slopes, snow), gyaru, fashion, trendy, gentle hair'},
    {'name': '旗袍风(Cheongsam)',
     'img': './style_image/Cheongsam.jpg',
     'model_id': 'PaperCloud/zju19_minguo_style_lora',
     'revision': 'v1.0.0',
     'bin_file': 'qipao2.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 0.95,
     'add_prompt_style': 'white_cheongsam, photography, warm light, Chinese classical indoor scene, close-up, front view, earrings, hairpin, serenity, elegant, facing the camera with a smile, beautiful chinese embroidery, symmetrical short sleeves'},
    {'name': '日系和服风(Kimono Style)',
     'img': './style_image/Kimono.jpg',
     'model_id': 'ZackWang123/filmvelvia_lora',
     'revision': 'v1.0.0',
     'bin_file': 'FilmVelvia3.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 0.95,
     'add_prompt_style': 'outdoor, (linen:1.4), cute japanese model girl, kimono, floral print, hair ornament, looking at viewer, hair flower, brown eyes, bangs, realistic'},
    {'name': '贵族公主风(Princess costum)',
     'img': './style_image/Princess_style.jpg',
     'model_id': 'AzilyModelScope/facechain_lora',
     'revision': 'v1.0.0',
     'bin_file': 'foreign_princess_costum.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'fantasy girl, close-up, Waist shot, long hair, jewelry, earrings, looking at viewer, white dress, cathedral background, crown, (detailed face, perfect face, perfect eyes, realistic eyes), (clear face), high detail, sharp focus, dramatic, beautiful girl'},
    {'name': '机械风(Mechanical)',
     'img': './style_image/Mechnical.jpg',
     'model_id': 'rewfueranro/Mechanical_lora',
     'revision': 'v1.0.0',
     'bin_file': 'reelmech1v2.safetensors',
     'multiplier_style': 1,
     'multiplier_human': 0.95,
     'add_prompt_style': 'looking to the camera , clean face, Masterpiece, top quality, official art, beautiful and aesthetic, a full portrait of a futuristic dystopian city,  scrapper,  intricate, elegant, highly detailed, sharp focus,  cyberpunk, luminescence: 1.3, transparency,  8K, stunning art, digital photography, painting, hyper-realistic art: 1.3, mechanical woman, art by Genevieve Valentine: 1.2, Nikon D850, F/8, reelmech, demonic, expressive, hypnotic, delicate, moody, alluring, perfect shading, HDR, photorealistic: 1.6'},
    {'name': '林中鹿女风(deer girl)',
     'img': './style_image/Deer_girl.jpg',
     'model_id': 'EnlZhao/deer_lora',
     'revision': 'v3.2.0',
     'bin_file': 'deer.safetensors',
     'multiplier_style': 0.5,
     'multiplier_human': 0.95,
     'add_prompt_style': 'bust shot, an elk girl in pink forest, smile, keep eyes staring at the camera, detailed antlers, monochrome ears, white dress, slim body, long hair, natural lighting, warm sunlight, light pink atmosphere, outdoor photo, field of pink maple leaves, flower, realistic, best quality'},
    {'name': '漫画风(cartoon)',
     'img': './style_image/cartoon.jpg',
     'model_id': 'rewfueranro/cartoon_lora',
     'revision': 'v1.0.0',
     'bin_file': 'cartoon.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'Manhuanan,jewelry,1boy,<lora:Manhuanan_20230827182922-000009:1>,half body photo,white hair,at the coffee shop,blurred background,CG,UE5'},
    {'name': '休闲生活风(Casual Lifestyle)',
     'img': './style_image/Casual_Lifestyle.jpg',
     'model_id': 'theRealSlimShady/AI_portraits',
     'revision': 'v2',
     'bin_file': 'PortaitMasterV1.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'smile, lips, put on makeup, wearing casual clothes, simple background, blurred background'},
    {'name': '梅花女孩(Chinese Girl among Plum Blossoms)',
     'img': './style_image/Chinese_Girl_among_Plum_Blossoms.jpg',
     'model_id': 'theRealSlimShady/AI_portraits',
     'revision': 'v2',
     'bin_file': 'edgFae_FINAL.safetensors',
     'multiplier_style': 0.4,
     'multiplier_human': 0.9,
     'add_prompt_style': 'chinese, wearing traditional chinese clothes, plum blossoms, wearing florescent makeup'},
    {'name': '芭比娃娃(Barbie Doll)',
     'img': './style_image/Barbie_Doll.jpg',
     'model_id': 'theRealSlimShady/AI_portraits',
     'revision': 'v2',
     'bin_file': 'PinkBarbie.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'golden blond hair, wearing frilly dress, bow and ponytail, exquisite background, pure color background, delicate earrings and necklace, solo, happy expression'},
    {'name': '白月光(Innocent Girl in White Dress)',
     'img': './style_image/Innocent_Girl_in_White_Dress.jpg',
     'model_id': None,
     'revision': None,
     'bin_file': None,
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wearing elegant white dress, simple pure color background, face located in the center of the picture, long black hair, inquisitive eyes, innocent expression, lips'},
    {'name': '优雅公主(Elegant Princess)',
     'img': './style_image/Elegant_Princess.jpg',
     'model_id': 'theRealSlimShady/AI_portraits',
     'revision': 'v2',
     'bin_file': 'blancanievesV2.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'short black wavy hair, pale complexion, white lace, sky-blue dress, puff sleeves, earings, necklace, happy expression, simple pure color background'},
    {'name': '鬼马少女(Pixy Girl)',
     'img': './style_image/Pixy_Girl.jpg',
     'model_id': 'theRealSlimShady/AI_portraits',
     'revision': 'v2',
     'bin_file': 'VidiaTinkerbellDisney-08.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'purple hair, ponytail, wearing slip skirt,looking straight into the camera with shoulders parallel to the frame, light purple background'},
    {'name': '夏日海滩风(Summer Ocean Vibe)',
     'img': './style_image/Ocean_Summer_vibe.jpg',
     'model_id': 'JeffVan/Oil_Paint_Style_LORA',
     'revision': 'v1.0.0',
     'bin_file': 'OilPaint.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'summer vibe,(ocean, rock, seawave, palm tree) sunshine,rim lighting, two tone light,  professional photoportait, beautiful eyes, beautiful face, ocean background, Style by NTY:1.3, (detailed face, perfect face, perfect eyes, realistic eyes)'},
    {'name': '京剧名旦风(Female role in Peking opera)',
     'img': './style_image/PekingOpera_female_role.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v1.0.0',
     'bin_file': 'PekingOperaR.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 0.95,
     'add_prompt_style': 'portraits,standing, (photorealistic:1.4), official art, unity 8k wallpaper, ultra detailed, beautiful and aesthetic, masterpiece, (fractal art), 1girl, bust, wide aperture, Peking Opera, light makeup, Close-up of the face, the face is clear, no headdress, standing, black hair, each hand has five fingers'},
    {'name': '自然清冷风(Cool tones)',
     'img': './style_image/Cool_tones.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v1.0.0',
     'bin_file': 'cool_tones.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.95,
     'add_prompt_style': 'photorealisitc face, upper body, hyper realistic, best quality, ultra high res, (photorealistic:1.4), 1girl, best quality, masterpiece, detailed face, high def, beautiful, (cleavage:1.2), intricate full color portrait, sharp focus, natural lighting, subsurface scattering'},
    {'name': '白雪公主(Snow White)',
     'img': './style_image/Snow_white.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v1.0.0',
     'bin_file': 'blancanievesV2.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': 'snow white, princess, blue skirt, 1girl, medium breast, looking at viewer, close-up to head, smile, short hair, black hair, standing, brown eyes, hair bow, hairband, red bow, forest background'},
    {'name': '西部牛仔风(Cowboy style)',
     'img': './style_image/Cowboy.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v1.0.0',
     'bin_file': 'style_niuzai768.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.95,
     'add_prompt_style': 'western cowboy style,photography,best quality, realistic, photorealistic, intricate details, cinematic light,  clear line, ultra high res, short hair'},
    {'name': '炫彩少女风(Colorful rainbow style)',
     'img': './style_image/Colorful_rainbow.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v1.0.0',
     'bin_file': 'liuli2.safetensors',
     'multiplier_style': 0.25,
     'multiplier_human': 0.95,
     'add_prompt_style': 'standing, coloured glaze, Polychromatic prism effect, rainbowcore, iridescence/opalescence, glowing colors, aluminum foil, Glowing ambiance, (portrait:1.5), black starry night background, close-up to head, wearing camisole'},
    {'name': '中国新年风(Chinese New Year Style)',
     'img': './style_image/Chinese_New_Year.jpg',
     'model_id': 'houpeiran/mymodel',
     'revision': 'v2',
     'bin_file': 'aki.safetensors',
     'multiplier_style': 0.2,
     'multiplier_human': 0.95,
     'add_prompt_style': 'Chinese New Year, perfect red hanfu, long sleeves, standing, intricat bright red background, many Chinese laterns in background, red flowers, casual, clear lines'},
    {'name': '绿野仙踪(Wizard of Oz)',
     'img': './style_image/Wizard_of_Oz.jpg',
     'model_id': 'Rechycs/Wizard_lora',
     'revision': 'v1.0.0',
     'bin_file': 'Wizard_of_Oz.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.8,
     'add_prompt_style': 'OIL PAINTING,IMPRESSIONISM,medium full view, amidst the ancient woodland, the image captures the ethereal beauty of a young dryad. her long, braided red hair cascades like flames, entwining with (vines and flowers that form her ornate dress:1.2), the air is filled with colorful petals, and dappled sunlight paints a mesmerizing tapestry on the forest floor, dense foliage, gnarled roots and branches, beams of sunlight, ethereal, mysterious, wondrous, chiaroscuro, masterpiece, best quality,<lora:bichu-v0612 :0.6> BICHU,'},
    {'name': '藏族风(ZangZu Style)',
     'img': './style_image/ZangZu.jpg',
     'model_id': 'fffff1123/zangzu',
     'revision': 'v1.0.0',
     'bin_file': 'ZangZu_chillout-000004.safetensors',
     'multiplier_style': 0.55,
     'multiplier_human': 0.95,
    'add_prompt_style':'(masterpiece, best quality, hires:1.2),Zangzu,1girl,solo,sitting,lips,upper_body,beads necklace,snow,looking at viewer, blurry background, blurry hair edge, outdoors, ultra-detailed,'},
    {'name': '红发礼服风(Red Style)',
     'img': './style_image/Redstyle.jpg',
     'model_id': 'Tekhne/red',
     'revision': 'v1.0.0',
     'bin_file': 'edgAyre_AC6.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
    'add_prompt_style':'Masterpiece, best quality,edgQuality,smirk,smug, edgAyre, red hair,red eyes,dress,Haute_Couture, feathered top,woman wearing a Haute_Couture dress'},
     {'name': '多巴胺风格(Colourful Style)',
     'img': './style_image/Duobaan.jpg',
     'model_id': 'Tekhne/dubaan',
     'revision': 'v1.0.0',
     'bin_file': 'colorfashionstyle_v1.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style':'colorfashionstyle,light smile, orange and blue and red theme'},
      {'name': '国风(GuoFeng Style)',
     'img': './style_image/GuoFeng.jpg',
     'model_id': 'Tekhne/GuoFengchill',
     'revision': 'v1.0.0',
     'bin_file': 'GuoFeng_sd-000006.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
    'add_prompt_style':'(masterpiece, best quality, hires:1.2),GuoFeng, 1girl,solo,linen cloth,red_lips,solo_focus, standing,looking at viewer, ethereal background'},
      {'name': '复古风(Retro Style)',
     'img': './style_image/Retro_style.jpg',
     'model_id': 'HanYixuan1/Retro_style',
     'revision': 'v1.0.0',
     'bin_file': 'Retro_style.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.8,
     'add_prompt_style': '1990s, <lora:RetroFusion v1.0.0:1>,  1girl, woman looking out window, against glass, clothes,gray white and black ,black hair,misty beauty,glimmer,warm-toned,soft,sense of depth，Gauze texture，Solid fabric，low pixel，thin， face focusing，rough cloth，fit，Slight yellowing，autochrome photography，light and shade  contrast，dim，pale，color fading，Monastic dress，Drop hands naturally，no hands，Exclude hands，Blur the old city background'},
    {'name': '印度风(India)',
     'img': './style_image/india.jpg',
     'model_id': 'lljjcc/IndianSarres',
     'revision':'v1.0.0',
     'bin_file': 'Indian saree.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wear indian style costume, gold ornament, gorgeous background, upper_body, raw photo, masterpiece, solo, medium shot, high detail face, slim body, photorealistic, best quality, indian dance, indian street, street photography'},
    {'name': '海洋风(ocean)',
     'img': './style_image/DreamyOcean.jpg',
     'model_id': 'MushroomLyn/artist',
     'revision': 'v2.0.0',
     'bin_file': 'mine.safetensors',
     'multiplier_style': 0.5,
     'multiplier_human': 0.95,
     'add_prompt_style': 'delicate, gentle eye, ocean, white shirt, sunlit, upper_body, raw photo, masterpiece, solo, medium shot, high detail face, slim body, photorealistic, best quality'},
     {'name': '花园风(flowers)',
     'img': './style_image/outdoor.jpg',
     'model_id': 'lljjcc/outdoor',
     'revision': 'v1.0.0',
     'bin_file': 'outdoor photo_v2.0.safetensors',
     'multiplier_style': 0.86,
     'multiplier_human': 0.95,
     'add_prompt_style': 'girl,flower, upper_body, raw photo, masterpiece, solo, medium shot, high detail face, slim body, photorealistic, best quality'},
    {'name': '主题乐园风(Disneyland)',
     'img': './style_image/Disneyland.jpg',
     'model_id': 'rtxxxx/zju_05',
     'revision': 'v1.0.0',
     'bin_file': 'disneyland.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.9,
     'add_prompt_style': '1girl, Minnie Mouse headband, disneyland, (cute dress:1.3), black hair, (ears:1.1), looking at viewer, bokeh, sunshine, warm light'},
    {'name': '绿茵球场风(Soccer Field)',
     'img': './style_image/Soccer.jpg',
     'model_id': 'rtxxxx/zju_05',
     'revision': 'v1.0.0',
     'bin_file': 'soccer_field.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.9,
     'add_prompt_style': 'soccer uniform, warm light, sunlight, close-up, inside soccer field background, poly tail, blue sky, Nike logo'},
    {'name': '中华刺绣风(Embroidery)',
     'img': './style_image/Embroidery.jpg',
     'model_id': 'rtxxxx/zju_05',
     'revision': 'v1.0.0',
     'bin_file': 'embroidery.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.9,
     'add_prompt_style': 'DMajic, 1girl, Chinese embroidery, embroidery patterns in background, rich colors, silk robe, ultra resolutions, rich details, the art of light and shadow, gorgeous, close up, face shot'}, 
    {'name': '蒙古草原风(Mongolian)',
     'img': './style_image/Mongolian.jpg',
     'model_id': 'rtxxxx/zju_05',
     'revision': 'v1.0.0',
     'bin_file': 'mongolian.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.9,
     'add_prompt_style': 'mongolian style, mongolian traditional clothes, (linen:1.3), mongolian hair ornament, grass, photography, hills, sunlight, warm light, front view, female focus'},
     {'name': '梦幻深海风(Sea World)',
      'img': './style_image/Underwater.jpg',
      'model_id': 'rtxxxx/zju_05',
      'revision': 'v1.0.0',
      'bin_file': 'underwater.safetensors',
      'multiplier_style': 0.7,
      'multiplier_human': 0.9,
      'add_prompt_style': 'underwater, fish, sea life, aquatic, photography, upper body, masterpiece, cinematic angle, looking at viewer, coral'},
     {'name': '火红少女风(Flame Red Style)',
     'img': './style_image/flame_red_style1.jpg',
     'model_id': 'Hswich/wlop_offset',
     'revision': 'v1.0.0',
     'bin_file': 'wlop_offset.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.6,
     'add_prompt_style': 'wlop, 1girl, black gloves, black jacket, character request, commentary, earrings, ghostblade, gloves, hand up, jacket, jewelry, long hair, looking down, red hair, solo, ((masterpiece)) <lora:wlop_offset:1>,ruthlessness,golden ACC,locomotive'},
     {'name': '藏族服饰风(tibetan clothing style)',
     'img': './style_image/tibetan_clothing.jpg',
     'model_id': 'PeiPeiY/style_lora',
     'revision': 'v1',
     'bin_file': 'tibetan.safetensors',
     'multiplier_style': 0.55,
     'multiplier_human': 0.9,
     'add_prompt_style': 'extremely delicate and beautiful girls, (tibetan clothing style), ((fur hat)), long hair, colorful makeup, outdoor, delicate headwear'},
      {'name': '萧瑟秋天风(bleak autumn style)',
     'img': './style_image/bleak_autumn.jpg',
     'model_id': 'PeiPeiY/style_lora',
     'revision': 'v1',
     'bin_file': 'bleak_autumn.safetensors',
     'multiplier_style': 0.55,
     'multiplier_human': 0.9,
     'add_prompt_style': 'extremely delicate and beautiful girls, (bleak autumn scenary), asia, brown hair'},
      {'name': '秋日胡杨风(autumn populus euphratica style)',
     'img': './style_image/autumn_populus.jpg',
     'model_id': 'PeiPeiY/style_lora',
     'revision': 'v1',
     'bin_file': 'autumn_populus.safetensors',
     'multiplier_style': 0.55,
     'multiplier_human': 0.9,
     'add_prompt_style': 'extremely delicate and beautiful girls, (autumn populus euphratica scenary, 1girl)'},
    {'name': '丁达尔风(Tyndall Light)',
     'img': './style_image/Tyndall.jpg',
     'model_id': 'Cleaner/Tyndalleffect_Light',
     'revision': 'v1.0.0',
     'bin_file': 'Tyndall effect_Light v1.1.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.95,
     'add_prompt_style': 'Best Quality,Masterpiece,Ultra High Resolution,(Realisticity:1.4),Original Photo,Cinematic Lighting,1Girl,light rays,Tyndall effect,<lora:Tyndall effect_Light v1.1:0.6>,masterpiece, best quality, highly detailed,outdoor,soft light'},
    {'name': '哥特洛丽塔(Gothic Lolita)',
     'img': './style_image/li.jpg',
     'model_id': 'Cleaner/lo_dress_gothic_style2_v2',
     'revision': 'v1.0.0',
     'bin_file': 'lo_dress_gothic_style2_v2.safetensors',
     'multiplier_style': 0.4,
     'multiplier_human': 0.95,
     'add_prompt_style': 'Lolita dress, Gothic Lolita style, Clothes in black or burgundy tones, 1 girl, solo, realistic, photorealistic, masterpiece, best quality, ultra detailed, looking at viewer, standing, natural lighting, depth of field, Gothic castle, Medieval painting, Medieval murals, masterpiece, best quality, slim, long hair, dynamic pose, detailed background, lace-trimmed, with bowknot, upper_body, raw photo, masterpiece, solo, medium shot, high detail face, slim body, photorealistic,Large glass windows, European monumental architecture'},
    {'name': '复古风(retro style)',
     'img': './style_image/retro_style.jpeg',
     'model_id': 'Licht000/retro_style_lora',
     'revision': 'v1.0.0',
     'bin_file': 'lijiaxin.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, close-up, face shot, broad-shouldered blue jackets, high-waisted pants, black curly hair, dim yellow light, old movie filters, shallow depth of field, playful smiles, (naturally blurred background, shabby street:2), Yellowed photos, blurry figure'},
    {'name': '绅士风(gentleman style)',
     'img': './style_image/gentleman.jpeg',
     'model_id': 'Licht000/gentleman',
     'revision': 'v1.0.0',
     'bin_file': 'trkshgntlmn10.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1male, black classic suit, ties, bowties, wristwatches, cufflink, slicked back, bar background'},
    {'name': '西部牛仔风(west cowboy)',
     'img': './style_image/west cowboy.jpeg',
     'model_id': 'Licht000/cowboy',
     'revision': 'v1.0.0',
     'bin_file': 'James West-000196.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1male, Denim jackets, checkered shirts, leather vests, yellow wide-brimmed hats, bandanas, leather belts with silver buckles, short hair, handguns, horse, tough, desert background'},
    {'name': '嘻哈风(hiphop style)',
     'img': './style_image/hiphop.jpeg',
     'model_id': 'Licht000/hiphop',
     'revision': 'v1.0.1',
     'bin_file': 'edg90hh.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1male, baggy hoodies, sweatshirts, jeans, baseball caps, chunky gold chains, sunglasses, hoop earrings, braids, dreadlocks, graffiti wall background, street'},
    {'name': '洛丽塔(lolita)',
     'img': './style_image/lolita.jpeg',
     'model_id': 'Licht000/lolita',
     'revision': 'v1.0.0',
     'bin_file': 'lolitaV1.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, puffy dresses, lace edges, high-waist skirts, lace gloves, brooches, curled hair, braids, adorned with bows, rosy blush, pink lipsticks, reserved, sweet, girlish, garden background'},
    {'name': '女巫风(witch style)',
     'img': './style_image/witch.jpeg',
     'model_id': 'Licht000/witch',
     'revision': 'v1.0.0',
     'bin_file': 'Moon Witch.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, black robes, lace clothing, long skirts, capes, crystal ball, star and moon jewelry, black hats, and wands, dark wavy hair, adorned with mysterious hairpieces, dark eyeshadows, dark blush, forest background'},
    {'name': '女仆风(maid style)',
     'img': './style_image/maid.jpeg',
     'model_id': 'Licht000/maid',
     'revision': 'v1.0.0',
     'bin_file': 'maid_attire_v2.safetensors',
     'multiplier_style': 0.3,
     'multiplier_human': 0.95,
     'add_prompt_style': '1girl, black or white short dresses, lace edges, aprons, bows, lace gloves, neckties, cuffs, twin-tails, light makeup, pink blush, pink lipsticks, gentle, considerate, cafe background'},
    {'name': '圣诞风(Christmas)',
     'img': './style_image/Christmas.jpg',
     'model_id': 'mowunian/christmas',
     'revision': 'v1.0.0',
     'bin_file': 'christmas.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'christmas, christmas tree, dress, sweater, snowing, gift, gift box, bell'},
    {'name': '敦煌风(Dunhuang)',
     'img': './style_image/Dunhuang.jpg',
     'model_id': 'PaperCloud/zju19_dunhuang_style_lora',
     'revision': 'v2',
     'bin_file': 'dunhuangV3.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 1.05,
     'add_prompt_style':'(close-up),(((faceshort))),black long hair, (clean face), dunhuang, Chinese ancient style, clean skin, organza_lace, Dunhuang wind, Art deco, Necklace, jewelry, Bracelet, Earrings, dunhuang_style, see-through_dress, Expressionism, looking towards the camera'},
    {'name': '苗族服装风(Miao style)',
     'img': './style_image/miaozu.jpg',
     'model_id': 'SoulNut/facechain_model',
     'revision': 'v3.0',
     'bin_file': 'miaozu.safetensors',
     'multiplier_style': 0.45,
     'multiplier_human': 0.9,
     'add_prompt_style': '(masterpiece, ultra high res face, face ultra zoom, highres, best quality, ultra detailed, portrait:1.2), sfw, Miao nationality, smaller head, beautiful face, smaller face, ((intricate embroideries on clothes)), silver ornaments, ((intricate detailed headdresses)), (((extremely elaborate silver detailing))), exquisite and ornate headpiece featuring intricate filigree designs and delicate engravings, leaning against a stone archway, hands clasped behind, wear gloves, detailed fingers,  Miao Village background, flat chest, realistic'},
    {'name': '时尚墨镜风(fashionglasses)',
     'img': './style_image/fashionglasses.jpg',
     'model_id': 'SoulNut/facechain_LoRA',
     'revision': 'v1.1',
     'bin_file': 'fashion_glasses.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.95,
     'add_prompt_style': '(masterpiece, ultra high res face, face ultra zoom, highres, best quality, ultra detailed, cinematic lighting, portrait:1.2), sfw, short hair, blonde-glasses,solo,close-up,red lips,facing aside, cityscape, detailed background, blonde Leather clothing, blonde theme'},
    {'name': '男士西装风(Men\'s Suit)',
     'img': './style_image/men_suit.jpg',
     'model_id': 'potazinc/suit',
     'revision': 'v2',
     'bin_file': 'businessman-AIX.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.95,
     'add_prompt_style': '(realistic:1.2), HDR, UHD, 8K, face ultra zoom, portrait, male, (1boy, office man, adult, asian, black hair,  suit, hand in pocket, close-up)'},
     {'name': '科幻风(science fiction style suit)',
     'img': './style_image/science_fiction.jpg',
     'model_id': 'StigXI/zju_01_LoRA',
     'revision': 'v1.0.0',
     'bin_file': 'scific.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'science fiction style suit,tidy face, photography, clean, vivid colors, (clean face:1.5), highly detailed, UHD, professional, cyber punk street background'},
    {'name': '中国风(traditional chinese style suit)',
     'img': './style_image/chinese_traditional.jpg',
     'model_id': 'StigXI/zju_01_LoRA',
     'revision': 'v1.0.0',
     'bin_file': 'chinese.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'traditional chinese suit, face shot, clean, different colors, (natural collar:1.5), tidy clothing, close-up, full head, stduio lighting, Bokeh, vivid colors, sunny, HDR, studio lighting, highly detailed, traditional chinese park background'},
    {'name': '西部风(wild west style)',
     'img': './style_image/wild_west.jpg',
     'model_id': 'StigXI/zju_01_LoRA',
     'revision': 'v1.0.0',
     'bin_file': 'west.safetensors',
     'multiplier_style': 0.35,
     'multiplier_human': 0.95,
     'add_prompt_style': 'wild west style clothing, vivid colors, west countryside, front view, grassland, HDR, studio lighting, highly detailed, trending on artstation'},
    {'name': '漫游宇航员(Roaming Astronaut)',
     'img': './style_image/Roaming_Astronaut.png',
     'model_id':'idlepiggy/zju_16FC',
     'revision': 'v3.0.1',
     'bin_file': 'firmamentV2.1.safetensors',
     'multiplier_style': 0.7,
     'multiplier_human': 0.9,
     'add_prompt_style': 'firmament,space_helmet,background is universe with stars,moon,looking at viewer'},
    {'name': '复古军装风(Retro military uniform)',
     'img': './style_image/jun_zhuang.png',
     'model_id': 'idlepiggy/zju_16FC',
     'revision': 'v3.0.1',
     'bin_file': 'minguojunzhuangv1.0.safetensors',
     'multiplier_style': 0.65,
     'multiplier_human': 0.9,
     'add_prompt_style': 'fall, wall behind, blurry, blurry background, depth of field, gloves, hat,  realistic, solo, uniform, black hair, long sleeves, black gloves, cape, military, black headwear, military uniform, peaked cap, military hat, looking at viewer,front view'},
    {'name': '花环洛丽塔(Flora Lolita)',
     'img': './style_image/luolita.png',
     'model_id': 'idlepiggy/zju_16FC',
     'revision': 'v3.0.1',
     'bin_file': 'lolitaV1.safetensors',
     'multiplier_style': 0.6,
     'multiplier_human': 0.95,
     'add_prompt_style': 'lolita, warm sunlight, front view, jewelry,summer,purple eyes,long hair, white dress,backgound is sun and rainbow,faceing camera with a smile,beautiful flower on the head'},
]

pose_models = [
    {'name': '无姿态控制(No pose control)'},
    {'name': 'pose-v1.1-with-depth'},
    {'name': 'pose-v1.1'}
]

pose_examples = {
    'man': [
        ['./poses/man/pose1.png'],
        ['./poses/man/pose2.png'],
        ['./poses/man/pose3.png'],
        ['./poses/man/pose4.png']
    ],
    'woman': [
        ['./poses/woman/pose1.png'],
        ['./poses/woman/pose2.png'],
        ['./poses/woman/pose3.png'],
        ['./poses/woman/pose4.png'],
    ]
}